import numpy as np


def window_eeg_signal(data, sfreq, window_sec=10, step_sec=5):
    """
    Split EEG data into overlapping windows.

    Parameters
    ----------
    data : np.ndarray
        EEG signal. Can be:
        - 1D: (n_samples,)
        - 2D: (n_channels, n_samples)
    sfreq : int or float
        Sampling frequency in Hz.
    window_sec : int or float
        Window length in seconds.
    step_sec : int or float
        Step between consecutive windows in seconds.

    Returns
    -------
    list
        List of EEG windows.
    """

    data = np.asarray(data)

    # EEG samples are assumed to be on the last axis
    n_samples = data.shape[-1]

    window_samples = int(window_sec * sfreq)
    step_samples = int(step_sec * sfreq)

    if n_samples < window_samples:
        print(
            f"[WARNING] Data length {n_samples / sfreq:.2f} sec "
            f"is shorter than the requested {window_sec} sec window."
        )
        return [data]

    windows = []

    for start in range(
        0,
        n_samples - window_samples + 1,
        step_samples
    ):
        end = start + window_samples

        # Works for both 1D and multi-channel EEG
        window = data[..., start:end]

        windows.append(window)

    print(f"[DEBUG] Created {len(windows)} windows")

    return windows


def label_windows_with_preictal(
    windows,
    seizure_start,
    preictal_sec=300,
    sampling_rate=256,
    step_sec=5
):
    """
    Label EEG windows as non-preictal (0) or preictal/seizure-related (1).

    A window is labelled 1 when it overlaps the preictal interval
    immediately preceding seizure onset.

    Parameters
    ----------
    windows : list
        EEG windows generated by window_eeg_signal().
    seizure_start : float
        Seizure onset time in seconds.
    preictal_sec : int or float
        Duration of the preictal interval before seizure onset.
    sampling_rate : int or float
        EEG sampling frequency.
    step_sec : int or float
        Step between consecutive windows.

    Returns
    -------
    list
        Binary labels:
        0 = non-preictal
        1 = preictal / seizure-related
    """

    labels = []

    preictal_start = max(0, seizure_start - preictal_sec)

    for i, window in enumerate(windows):

        window_start = i * step_sec
        window_duration = window.shape[-1] / sampling_rate
        window_end = window_start + window_duration

        # Check whether the window overlaps the preictal interval
        if (
            window_end >= preictal_start
            and window_start <= seizure_start
        ):
            label = 1
        else:
            label = 0

        labels.append(label)

    print(
        f"[DEBUG] Labeled {len(labels)} windows "
        f"(preictal/seizure-related: {sum(labels)})"
    )

    return labels